services:
  - type: web
    name: cobranzas-backend
    runtime: node
    buildCommand: bash build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: SUPABASE_URL
        fromDatabase: SUPABASE_URL
      - key: SUPABASE_SERVICE_KEY
        fromDatabase: SUPABASE_SERVICE_KEY
      - key: PORT
        value: 3000
      - key: MAIL_USER
        fromDatabase: MAIL_USER
      - key: MAIL_PASS
        fromDatabase: MAIL_PASS
      - key: MAIL_FROM
        value: Cobranzas ASAP <kamiruberto100@gmail.com>
